# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TmmGeek
brief-intro: Artificial Intelligence and Big Data student
baseurl: "/TmmGeekBlog" # the subpath of your site, e.g. /blog
url: "http://www.tmmlab.com" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: JizongLiang
facebook_username: jizong.liang
github_username:  JizongL
email: 2015rpro@gmail.com
weibo_username: ΤmmGeek
zhihu_username: TmmGeek
linkedIn_username: jizongliang
dribbble_username: JizongLiang

description_footer: Computer and Math related

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: tmmgeek
disqus_shortname: #gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
## baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-89660816-1 # google 分析追踪id

# Build settings
markdown: kramdown
# markdown: redcarpet
# highlighter: pygments
contact_PK: 970b952628537ad7a2e389fdd91bd127

# for mathjax markdown display, also see 
redcarpet: 

extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
gravatar_md5:    0f8154e563aa3319f1ebc77be5fca304
# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
